@extends('layouts.app')
@section('title', 'Reservar máquina')
@section('content')
<div class="page-heading"><div><div class="eyebrow red">UN TURNO QUE SE ADAPTA A TI</div><h1>Reserva tu máquina</h1><p>Elige cuándo venir y encuentra tu máquina disponible.</p></div><span class="date-chip"><x-icon name="calendar"/> {{ $active }} de 3 reservas activas</span></div>
@if($active >= 3)<div class="alert error"><x-icon name="info"/>Ya tienes el máximo de 3 reservas activas. Cancela una pendiente o recoge tu ropa para reservar de nuevo.</div>@endif
<section class="panel"><div class="section-heading"><div><h2><span class="number-step">1</span> Elige fecha y horario</h2><p>Turnos de una hora · Horario de Bolivia</p></div></div><form class="filter-bar booking-filter" method="GET"><label>Fecha de tu reserva<input type="date" name="date" value="{{ $date }}" min="{{ today()->toDateString() }}" max="{{ today()->addDays(30)->toDateString() }}" required></label><label>Horario<select name="time">@foreach(range(8,19) as $hour)@php($value = sprintf('%02d:00', $hour))<option value="{{ $value }}" @selected($time === $value)>{{ $value }} – {{ sprintf('%02d:00', $hour+1) }}</option>@endforeach</select></label><button class="button"><x-icon name="search"/> Consultar disponibilidad</button></form></section>
<div class="section-heading standalone"><div><h2><span class="number-step">2</span> Elige una máquina</h2><p>Disponibilidad para el {{ $start->format('d/m/Y') }}, de {{ $time }} a {{ $start->copy()->addHour()->format('H:i') }}.</p></div><span class="muted">{{ $machines->count() }} máquinas</span></div>
<div class="machine-grid">@forelse($machines as $machine)@php($busy = in_array($machine->id, $occupied))@php($maintenance = $machine->status !== 'disponible')@php($disabled = $busy || $maintenance || $start->isPast() || $active >= 3)
<article class="machine-card"><div class="machine-visual {{ $maintenance ? 'maintenance' : '' }}"><span class="status {{ $maintenance ? 'pendiente' : ($busy ? 'en_proceso' : 'listo') }}">{{ $maintenance ? 'Mantenimiento' : ($busy ? 'Ocupada en este turno' : 'Disponible en este turno') }}</span><x-icon class="big-washer"/></div><div class="machine-details"><div class="machine-title"><h3>{{ $machine->name }}</h3><span>{{ $machine->capacity }} kg</span></div><p>{{ ucfirst($machine->type) }} · Ciclo de 60 minutos</p><div class="location"><x-icon name="pin"/> {{ $machine->location }}</div><form method="POST" action="{{ route('reservations.store') }}" data-confirm="¿Reservar {{ $machine->name }} el {{ $start->format('d/m/Y') }} de {{ $time }} a {{ $start->copy()->addHour()->format('H:i') }}?">@csrf<input type="hidden" name="machine_id" value="{{ $machine->id }}"><input type="hidden" name="date" value="{{ $date }}"><input type="hidden" name="time" value="{{ $time }}"><button class="button full {{ $disabled ? 'secondary' : '' }}" @disabled($disabled)>{{ $disabled ? ($maintenance ? 'No disponible' : ($busy ? 'Elige otro turno' : ($active >= 3 ? 'Límite de reservas' : 'Horario finalizado'))) : 'Reservar esta máquina' }} @unless($disabled)<x-icon name="arrow"/>@endunless</button></form></div></article>
@empty<div class="panel empty-state"><h3>Aún no hay máquinas</h3><p>El personal está preparando la lavandería. Vuelve a consultar más tarde.</p></div>@endforelse</div><div class="inline-note"><x-icon name="info"/><span>Puedes tener hasta 3 reservas activas y reservar con 30 días de anticipación. Solo las reservas pendientes pueden cancelarse.</span></div>
@endsection
